# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'identaxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for identaxy
  pod 'PopBounceButton'
  pod "Shuffle-iOS"
  pod "SwiftGifOrigin"  
  # Pods for firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
end
