# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'identaxy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for identaxy
  pod 'PopBounceButton'
  pod 'pop', '~> 1.0'
  pod "Koloda"
  
  # Pods for firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
end
